# Generated by Django 3.1.5 on 2021-01-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=125)),
                ('job_description', models.TextField(max_length=500)),
                ('job_requirements', models.TextField(max_length=125)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_type', models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship')], max_length=15)),
                ('skill_type', models.CharField(choices=[('Web Developer', 'Web Developer'), ('Wordpress Developer', 'Wordpress Developer'), ('Desginer', 'Designer'), ('Content Writing', 'Content Writing')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CareerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='job_form_photo')),
                ('cv', models.FileField(upload_to='job_form_cv')),
                ('your_strength_description', models.TextField(max_length=150)),
                ('how_did_you_know_about_us', models.CharField(max_length=50)),
                ('referred_by', models.CharField(blank=True, max_length=100)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doerscareer.career')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='career_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doerscareer.careercategory'),
        ),
    ]
