# Generated by Django 3.1.5 on 2021-01-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doerscareer', '0002_auto_20210131_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=125)),
                ('job_description', models.TextField(max_length=500)),
                ('job_requirements', models.TextField(max_length=125)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('career_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doerscareer.careercategory')),
            ],
        ),
        migrations.CreateModel(
            name='CareerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='job_form_photo')),
                ('cv', models.FileField(upload_to='job_form_cv')),
                ('your_strength_description', models.TextField(max_length=150)),
                ('how_did_you_know_about_us', models.CharField(max_length=50)),
                ('referred_by', models.CharField(blank=True, max_length=100)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doerscareer.career')),
            ],
        ),
    ]
