# Generated by Django 3.1.5 on 2021-01-31 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default_profile_picture.jpg', null=True, upload_to='blog_images')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
